### ISSUE TITLE
Is request cancellation supported

### ISSUE THREAD

**Issue by ryanmk54** [victor-am/rails-ranger#42]
Is request cancellation supported like it is in Axios?
https://github.com/axios/axios#cancellation

**Comment by victor-am** [comment]
Hmmm, if axios 0.19.0 supports it I believe yes since we just forward the params you pass to the request into axios itself.

If not then we could bump the axios version in the project (it's fairly simple, if you are interested in doing it and opening a PR feel free to 😄 otherwise I can do it in a few days).

**Comment by ryanmk54** [comment]
I have some other bugs that I need to fix first, but if I get time I would like to add a cancellation section to the documentation. Not sure when I'll get to it though.

**Comment by victor-am** [comment]
Solved by https://github.com/victor-am/rails-ranger/pull/43
